---
- name: Download Elasticsearch package
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ ES_VERSION }}.deb"
    dest: "{{ DEB_PACKAGES_DOWNLOAD_DIR }}/elasticsearch-{{ ES_VERSION }}.deb"

- name: Install Elasticsearch package
  apt: deb="{{ DEB_PACKAGES_DOWNLOAD_DIR }}/elasticsearch-{{ ES_VERSION }}.deb"

- name: Change Elasticsearch host
  lineinfile:
    dest: "/etc/elasticsearch/elasticsearch.yml"
    regexp: "network.host"
    line: "network.host = [_local_, _site_]"
  become: yes
  notify: Restart elasticsearch
