---
- name: Download Elasticsearch package
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ ES_VERSION }}.deb"
    dest: "{{ DEB_PACKAGES_DOWNLOAD_DIR }}/elasticsearch-{{ ES_VERSION }}.deb"

- name: Install Elasticsearch package
  apt: deb="{{ DEB_PACKAGES_DOWNLOAD_DIR }}/elasticsearch-{{ ES_VERSION }}.deb"
