---
- shell: rm -rf /etc/apt/sources.list.d/.*webupd8team-java.list.*
  become: yes
  become_user: root
  become_method: sudo

- apt: update_cache=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  become: yes
  become_user: root
  become_method: sudo

- apt: update_cache=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install Oracle Java 8
  apt: name={{item}}
  with_items:
    - oracle-java8-installer
  become: yes
  become_user: root
  become_method: sudo
