---
- name: Change MySQL bind-address
  lineinfile:
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: "bind-address"
    line: "bind-address = 0.0.0.0"
  notify:
      - Restart MySQL

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ MYSQL_ROOT_PASSWORD }} state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify:
      - Restart MySQL

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  notify:
    - Restart MySQL