---
- name: Install MySQL
  apt: name=mysql state=latest

- name: MySQL config file
  template:
    src=mysqld.cnf
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    owner=root group=root mode=644
  become: yes

- name: Change MySQL bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: 'bind-address'
    line: 'bind-address = 0.0.0.0'