---
- name: Install MySQL packages
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb

- name: Change MySQL bind-address
  lineinfile:
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: "bind-address"
    line: "bind-address = 0.0.0.0"
