---
- name: Download Kibana package
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ KIBANA_VERSION }}-amd64.deb"
    dest: "{{ DEB_PACKAGES_DOWNLOAD_DIR }}/kibana-{{ KIBANA_VERSION }}-amd64.deb"

- name: Install Kibana package
  apt: deb="{{ DEB_PACKAGES_DOWNLOAD_DIR }}/kibana-{{ KIBANA_VERSION }}-amd64.deb"
